<?php
/**
 * Created by PhpStorm.
 * User: chenhongjin
 * Date: 2018/11/19
 * Time: 21:30
 */

namespace app\api\controller\lvyou;


use app\admin\model\LvyouOrderLog;
use app\common\controller\ControllerBase;
use think\Controller;
use think\Loader;
use think\Request;

/**
 *  核验订单
 * @author: chenhg <945076855@qq.com>
 * Copyright in Highnes
 * @package app\api\controller\lvyou
 */
class Check extends ControllerBase
{
    private $uid = 0;

    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
        $this->uid        = session('user_id');
        $params           = input();
        $params['router'] = str_replace('/', '-', 'api/lvyou/check');

        if (!$this->uid) {
            $this->redirect(config('setting.site_url') . url('api/lvyou/h5login', $params));
        }


        $this->getWebInfo();
        $this->getSignPackage();

    }

    public function index()
    {
        $ordersn = input('order_sn');

        $is_admin = \app\common\model\Member::where("id", $this->uid)->value('is_admin');
        if ($is_admin != 1) { // 是管理员
            $this->redirect('api/lvyou/checkSucc', ['ordersn' => $ordersn, 'msg' => '非工作人员']);
        }
        $where['order_sn|id'] = $ordersn;
        $info                 = \app\common\model\LvyouOrder::where($where)->find();
        if (empty($info)) {
            $this->redirect('api/lvyou/checkSucc', ['ordersn' => $ordersn, 'msg' => '二维码不存在']);
        }
        if ($info['order_status'] < 10) { // 订单未支付
            $this->redirect('api/lvyou/checkSucc', ['ordersn' => $ordersn, 'msg' => '订单未支付']);
        }
        if ($info['order_status'] != 10) {// 已退款或已使用
            $this->redirect('api/lvyou/checkSucc', ['ordersn' => $ordersn, 'msg' => '失效二维码']);
        }

        $res = \app\common\model\LvyouOrder::where($where)->update(['finish_time' => time(), 'order_status' => 14]);
        LvyouOrderLog::addLog($info['id'], $info['uid'], '订单验票成功');
        if ($res) {
            $this->redirect('api/lvyou/checkSucc', ['ordersn' => $ordersn, 'msg' => '验票成功']);
        }
    }

    public function succ()
    {
        $this->assign('date', date('Y-m-d'));
        return $this->fetch('check/succ');
    }

    public function getWebInfo($title = '', $desc = '', $logo = '')
    {

        $webInfo = [
            'title'    => $title ?: '研学旅游',
            'shareUrl' => config('setting.site_url') . url(Request::instance()->module() . '/' . Request::instance()->controller() . '/' . Request::instance()->action(), input()),
            'web_desc' => $desc ?: '研学旅游验票端',
            'logo'     => $logo ?: config('setting.site_url') . '/static/check/images/e2.png',
        ];
        $this->assign('webInfo', $webInfo);
    }


    public function getSignPackage()
    {
        Loader::import("WeChat.Jssdk");
        $jssdk       = new  \JSSDK();
        $signPackage = $jssdk->getSignPackage();

        $this->assign('signPackage', $signPackage);
    }

}